# Generated by Django 5.2.4 on 2025-08-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_at_alter_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Example-slug', unique=True),
            preserve_default=False,
        ),
    ]
